// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxzXMxfZ7hOb9SnSK2HCCaRcO1DkAq5Q',
    appId: '1:423393892480:web:ba0a75e21fc189ba2b6e65',
    messagingSenderId: '423393892480',
    projectId: 'audreysunflower-43a8b',
    authDomain: 'audreysunflower-43a8b.firebaseapp.com',
    storageBucket: 'audreysunflower-43a8b.firebasestorage.app',
    measurementId: 'G-G50XXNCMWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5LQCUfDsgVi51jND5HrVD0HpsvFlIHAQ',
    appId: '1:423393892480:android:36bd2f6dea67f9ea2b6e65',
    messagingSenderId: '423393892480',
    projectId: 'audreysunflower-43a8b',
    storageBucket: 'audreysunflower-43a8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIsDtkOEV_uGfBuTkoI_xEcZ04tysyMuM',
    appId: '1:423393892480:ios:806fbf8da9f2b7172b6e65',
    messagingSenderId: '423393892480',
    projectId: 'audreysunflower-43a8b',
    storageBucket: 'audreysunflower-43a8b.firebasestorage.app',
    iosBundleId: 'com.example.sunflower',
  );

}